services:
  litellm:
    # build:
      # context: .
      # args:
        # target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./custom_callbacks.py:/app/custom_callbacks.py
      - ./custom_auth.py:/app/custom_auth.py
      - ./system_prompt.txt:/app/system_prompt.txt
    command:
      - "--config=/app/config.yaml"
    ##############################################
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    restart: always
    environment:
      DATABASE_URL: "postgresql://mabruk:mabruk2039@185.241.4.161:5432/litellm"
      STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
      LITELLM_MASTER_KEY: "see_in_env_secret_cannot_upload_to_github"
      LITELLM_SALT_KEY: "see_in_env_secret_cannot_upload_to_github"
    env_file:
      - .env # Load local .env file
    healthcheck:  # Defines the health check configuration for the container
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1" ]  # Command to execute for health check
      interval: 30s  # Perform health check every 30 seconds 
      timeout: 10s   # Health check command times out after 10 seconds
      retries: 3     # Retry up to 3 times if health check fails
      start_period: 40s  # Wait 40 seconds after container start before beginning health checks

volumes:
  postgres_data:
    name: litellm_postgres_data # Named volume for Postgres data persistence
